export const itemsDataSet = [
  {
    dataset_id: 1,
    dataset_order: 10,
    dataset_name: "EUFO_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "treecover",
    use_for_risk: 1,
  },
  {
    dataset_id: 2,
    dataset_order: 20,
    dataset_name: "GLAD_Primary",
    presence_only_flag: 0,
    exclude: 0,
    theme: "treecover",
    use_for_risk: 1,
  },
  {
    dataset_id: 3,
    dataset_order: 30,
    dataset_name: "TMF_undist",
    presence_only_flag: 0,
    exclude: 0,
    theme: "treecover",
    use_for_risk: 1,
  },
  {
    dataset_id: 4,
    dataset_order: 40,
    dataset_name: "JAXA_FNF_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "treecover",
    use_for_risk: 1,
  },
  {
    dataset_id: 5,
    dataset_order: 50,
    dataset_name: "GFC_TC_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "treecover",
    use_for_risk: 1,
  },
  {
    dataset_id: 6,
    dataset_order: 60,
    dataset_name: "GLAD_LULC_2020",
    presence_only_flag: 0,
    exclude: 1,
    theme: "treecover",
    use_for_risk: 0,
  },
  {
    dataset_id: 7,
    dataset_order: 70,
    dataset_name: "ESA_TC_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "treecover",
    use_for_risk: 1,
  },
  {
    dataset_id: 8,
    dataset_order: 80,
    dataset_name: "ESRI_TC_2020",
    presence_only_flag: 0,
    exclude: 1,
    theme: "treecover",
    use_for_risk: 0,
  },
  {
    dataset_id: 9,
    dataset_order: 90,
    dataset_name: "TMF_disturbed",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 10,
    dataset_order: 100,
    dataset_name: "TMF_plant",
    presence_only_flag: 0,
    exclude: 0,
    theme: "commodities",
    use_for_risk: 1,
  },
  {
    dataset_id: 11,
    dataset_order: 110,
    dataset_name: "Oil_palm_Descals",
    presence_only_flag: 0,
    exclude: 0,
    theme: "commodities",
    use_for_risk: 1,
  },
  {
    dataset_id: 12,
    dataset_order: 120,
    dataset_name: "Oil_palm_FDaP",
    presence_only_flag: 0,
    exclude: 0,
    theme: "commodities",
    use_for_risk: 1,
  },
  {
    dataset_id: 13,
    dataset_order: 130,
    dataset_name: "Cocoa_ETH",
    presence_only_flag: 0,
    exclude: 0,
    theme: "commodities",
    use_for_risk: 1,
  },
  {
    dataset_id: 14,
    dataset_order: 140,
    dataset_name: "Cocoa_bnetd",
    presence_only_flag: 0,
    exclude: 0,
    theme: "commodities",
    use_for_risk: 1,
  },
  {
    dataset_id: 15,
    dataset_order: 150,
    dataset_name: "WDPA",
    presence_only_flag: 1,
    exclude: 0,
    theme: "ancilliary",
    use_for_risk: 0,
  },
  {
    dataset_id: 16,
    dataset_order: 160,
    dataset_name: "OECM",
    presence_only_flag: 1,
    exclude: 1,
    theme: "ancilliary",
    use_for_risk: 0,
  },
  {
    dataset_id: 17,
    dataset_order: 170,
    dataset_name: "KBA",
    presence_only_flag: 1,
    exclude: 1,
    theme: "ancilliary",
    use_for_risk: 0,
  },
  {
    dataset_id: 18,
    dataset_order: 180,
    dataset_name: "TMF_def_2000",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 19,
    dataset_order: 190,
    dataset_name: "TMF_def_2001",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 20,
    dataset_order: 200,
    dataset_name: "TMF_def_2002",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 21,
    dataset_order: 210,
    dataset_name: "TMF_def_2003",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 22,
    dataset_order: 220,
    dataset_name: "TMF_def_2004",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 23,
    dataset_order: 230,
    dataset_name: "TMF_def_2005",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 24,
    dataset_order: 240,
    dataset_name: "TMF_def_2006",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 25,
    dataset_order: 250,
    dataset_name: "TMF_def_2007",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 26,
    dataset_order: 260,
    dataset_name: "TMF_def_2008",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 27,
    dataset_order: 270,
    dataset_name: "TMF_def_2009",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 28,
    dataset_order: 280,
    dataset_name: "TMF_def_2010",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 29,
    dataset_order: 290,
    dataset_name: "TMF_def_2011",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 30,
    dataset_order: 300,
    dataset_name: "TMF_def_2012",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 31,
    dataset_order: 310,
    dataset_name: "TMF_def_2013",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 32,
    dataset_order: 320,
    dataset_name: "TMF_def_2014",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 33,
    dataset_order: 330,
    dataset_name: "TMF_def_2015",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 34,
    dataset_order: 340,
    dataset_name: "TMF_def_2016",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 35,
    dataset_order: 350,
    dataset_name: "TMF_def_2017",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 36,
    dataset_order: 360,
    dataset_name: "TMF_def_2018",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 37,
    dataset_order: 370,
    dataset_name: "TMF_def_2019",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 38,
    dataset_order: 380,
    dataset_name: "TMF_def_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 39,
    dataset_order: 390,
    dataset_name: "TMF_def_2021",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 40,
    dataset_order: 400,
    dataset_name: "TMF_def_2022",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 41,
    dataset_order: 410,
    dataset_name: "TMF_deg_2000",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 42,
    dataset_order: 420,
    dataset_name: "TMF_deg_2001",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 43,
    dataset_order: 430,
    dataset_name: "TMF_deg_2002",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 44,
    dataset_order: 440,
    dataset_name: "TMF_deg_2003",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 45,
    dataset_order: 450,
    dataset_name: "TMF_deg_2004",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 46,
    dataset_order: 460,
    dataset_name: "TMF_deg_2005",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 47,
    dataset_order: 470,
    dataset_name: "TMF_deg_2006",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 48,
    dataset_order: 480,
    dataset_name: "TMF_deg_2007",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 49,
    dataset_order: 490,
    dataset_name: "TMF_deg_2008",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 50,
    dataset_order: 500,
    dataset_name: "TMF_deg_2009",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 51,
    dataset_order: 510,
    dataset_name: "TMF_deg_2010",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 52,
    dataset_order: 520,
    dataset_name: "TMF_deg_2011",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 53,
    dataset_order: 530,
    dataset_name: "TMF_deg_2012",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 54,
    dataset_order: 540,
    dataset_name: "TMF_deg_2013",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 55,
    dataset_order: 550,
    dataset_name: "TMF_deg_2014",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 56,
    dataset_order: 560,
    dataset_name: "TMF_deg_2015",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 57,
    dataset_order: 570,
    dataset_name: "TMF_deg_2016",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 58,
    dataset_order: 580,
    dataset_name: "TMF_deg_2017",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 59,
    dataset_order: 590,
    dataset_name: "TMF_deg_2018",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 60,
    dataset_order: 600,
    dataset_name: "TMF_deg_2019",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 61,
    dataset_order: 610,
    dataset_name: "TMF_deg_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 62,
    dataset_order: 620,
    dataset_name: "TMF_deg_2021",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 63,
    dataset_order: 630,
    dataset_name: "TMF_deg_2022",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 64,
    dataset_order: 640,
    dataset_name: "GFC_loss_year_2001",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 65,
    dataset_order: 650,
    dataset_name: "GFC_loss_year_2002",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 66,
    dataset_order: 660,
    dataset_name: "GFC_loss_year_2003",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 67,
    dataset_order: 670,
    dataset_name: "GFC_loss_year_2004",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 68,
    dataset_order: 680,
    dataset_name: "GFC_loss_year_2005",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 69,
    dataset_order: 690,
    dataset_name: "GFC_loss_year_2006",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 70,
    dataset_order: 700,
    dataset_name: "GFC_loss_year_2007",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 71,
    dataset_order: 710,
    dataset_name: "GFC_loss_year_2008",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 72,
    dataset_order: 720,
    dataset_name: "GFC_loss_year_2009",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 73,
    dataset_order: 730,
    dataset_name: "GFC_loss_year_2010",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 74,
    dataset_order: 740,
    dataset_name: "GFC_loss_year_2011",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 75,
    dataset_order: 750,
    dataset_name: "GFC_loss_year_2012",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 76,
    dataset_order: 760,
    dataset_name: "GFC_loss_year_2013",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 77,
    dataset_order: 770,
    dataset_name: "GFC_loss_year_2014",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 78,
    dataset_order: 780,
    dataset_name: "GFC_loss_year_2015",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 79,
    dataset_order: 790,
    dataset_name: "GFC_loss_year_2016",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 80,
    dataset_order: 800,
    dataset_name: "GFC_loss_year_2017",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 81,
    dataset_order: 810,
    dataset_name: "GFC_loss_year_2018",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 82,
    dataset_order: 820,
    dataset_name: "GFC_loss_year_2019",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 83,
    dataset_order: 830,
    dataset_name: "GFC_loss_year_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 84,
    dataset_order: 840,
    dataset_name: "GFC_loss_year_2021",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 85,
    dataset_order: 850,
    dataset_name: "GFC_loss_year_2022",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 86,
    dataset_order: 860,
    dataset_name: "GFC_loss_year_2023",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 87,
    dataset_order: 870,
    dataset_name: "RADD_year_2019",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 88,
    dataset_order: 880,
    dataset_name: "RADD_year_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 89,
    dataset_order: 890,
    dataset_name: "RADD_year_2021",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 90,
    dataset_order: 900,
    dataset_name: "RADD_year_2022",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 91,
    dataset_order: 910,
    dataset_name: "RADD_year_2023",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 92,
    dataset_order: 920,
    dataset_name: "RADD_year_2024",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 93,
    dataset_order: 930,
    dataset_name: "ESA_fire_2001",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 94,
    dataset_order: 940,
    dataset_name: "ESA_fire_2002",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 95,
    dataset_order: 950,
    dataset_name: "ESA_fire_2003",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 96,
    dataset_order: 960,
    dataset_name: "ESA_fire_2004",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 97,
    dataset_order: 970,
    dataset_name: "ESA_fire_2005",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 98,
    dataset_order: 980,
    dataset_name: "ESA_fire_2006",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 99,
    dataset_order: 990,
    dataset_name: "ESA_fire_2007",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 100,
    dataset_order: 1000,
    dataset_name: "ESA_fire_2008",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 101,
    dataset_order: 1010,
    dataset_name: "ESA_fire_2009",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 102,
    dataset_order: 1020,
    dataset_name: "ESA_fire_2010",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 103,
    dataset_order: 1030,
    dataset_name: "ESA_fire_2011",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 104,
    dataset_order: 1040,
    dataset_name: "ESA_fire_2012",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 105,
    dataset_order: 1050,
    dataset_name: "ESA_fire_2013",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 106,
    dataset_order: 1060,
    dataset_name: "ESA_fire_2014",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 107,
    dataset_order: 1070,
    dataset_name: "ESA_fire_2015",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 108,
    dataset_order: 1080,
    dataset_name: "ESA_fire_2016",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 109,
    dataset_order: 1090,
    dataset_name: "ESA_fire_2017",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 110,
    dataset_order: 1100,
    dataset_name: "ESA_fire_2018",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 111,
    dataset_order: 1110,
    dataset_name: "ESA_fire_2019",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 112,
    dataset_order: 1120,
    dataset_name: "ESA_fire_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 113,
    dataset_order: 1130,
    dataset_name: "MODIS_fire_2001",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 114,
    dataset_order: 1140,
    dataset_name: "MODIS_fire_2002",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 115,
    dataset_order: 1150,
    dataset_name: "MODIS_fire_2003",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 116,
    dataset_order: 1160,
    dataset_name: "MODIS_fire_2004",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 117,
    dataset_order: 1170,
    dataset_name: "MODIS_fire_2005",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 118,
    dataset_order: 1180,
    dataset_name: "MODIS_fire_2006",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 119,
    dataset_order: 1190,
    dataset_name: "MODIS_fire_2007",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 120,
    dataset_order: 1200,
    dataset_name: "MODIS_fire_2008",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 121,
    dataset_order: 1210,
    dataset_name: "MODIS_fire_2009",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 122,
    dataset_order: 1220,
    dataset_name: "MODIS_fire_2010",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 123,
    dataset_order: 1230,
    dataset_name: "MODIS_fire_2011",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 124,
    dataset_order: 1240,
    dataset_name: "MODIS_fire_2012",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 125,
    dataset_order: 1250,
    dataset_name: "MODIS_fire_2013",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 126,
    dataset_order: 1260,
    dataset_name: "MODIS_fire_2014",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 127,
    dataset_order: 1270,
    dataset_name: "MODIS_fire_2015",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 128,
    dataset_order: 1280,
    dataset_name: "MODIS_fire_2016",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 129,
    dataset_order: 1290,
    dataset_name: "MODIS_fire_2017",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 130,
    dataset_order: 1300,
    dataset_name: "MODIS_fire_2018",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 131,
    dataset_order: 1310,
    dataset_name: "MODIS_fire_2019",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 132,
    dataset_order: 1320,
    dataset_name: "MODIS_fire_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 0,
  },
  {
    dataset_id: 133,
    dataset_order: 1330,
    dataset_name: "MODIS_fire_2021",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 134,
    dataset_order: 1340,
    dataset_name: "MODIS_fire_2022",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 135,
    dataset_order: 1350,
    dataset_name: "MODIS_fire_2023",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 136,
    dataset_order: 1360,
    dataset_name: "MODIS_fire_2024",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 0,
  },
  {
    dataset_id: 137,
    dataset_order: 1370,
    dataset_name: "TMF_deg_before_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 1,
  },
  {
    dataset_id: 138,
    dataset_order: 1380,
    dataset_name: "TMF_def_before_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 1,
  },
  {
    dataset_id: 139,
    dataset_order: 1390,
    dataset_name: "GFC_loss_before_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 1,
  },
  {
    dataset_id: 140,
    dataset_order: 1400,
    dataset_name: "ESA_fire_before_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 1,
  },
  {
    dataset_id: 141,
    dataset_order: 1410,
    dataset_name: "MODIS_fire_before_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 1,
  },
  {
    dataset_id: 142,
    dataset_order: 1420,
    dataset_name: "RADD_before_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_before",
    use_for_risk: 1,
  },
  {
    dataset_id: 143,
    dataset_order: 1430,
    dataset_name: "TMF_deg_after_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 1,
  },
  {
    dataset_id: 144,
    dataset_order: 1440,
    dataset_name: "TMF_def_after_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 1,
  },
  {
    dataset_id: 145,
    dataset_order: 1450,
    dataset_name: "GFC_loss_after_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 1,
  },
  {
    dataset_id: 146,
    dataset_order: 1460,
    dataset_name: "MODIS_fire_after_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 1,
  },
  {
    dataset_id: 147,
    dataset_order: 1470,
    dataset_name: "RADD_after_2020",
    presence_only_flag: 0,
    exclude: 0,
    theme: "disturbance_after",
    use_for_risk: 1,
  },
];
